### ISSUE TITLE
마이페이지 프로필사진 클릭시 정보변경 버튼필요

### ISSUE THREAD

**Issue by ahnsungjoon** [2nd-market/2nd-market#12]

**Comment by sogoonii** [comment]
홈에서 한번에 정보변경 페이지로 이동 가능하도록 내비게이션 수정했습니다.

![image](https://user-images.githubusercontent.com/1967642/54808354-4dda5a00-4cc3-11e9-97bb-f2e86979210b.png)

**Comment by ahnsungjoon** [comment]
확인 했어요!
