### ISSUE TITLE
아이폰엑스에서 상품등록 버튼 터치 시 바로 등록이 안됨.

### ISSUE THREAD

**Issue by ahnsungjoon** [2nd-market/2nd-market#3]
iOS/사피리에서 상품등록 버튼 터치 시 하단 숨겨져있던 툴바가 올라오면서 상품등록이 바로 안되는 현상이 있음.

**Comment by sogoonii** [comment]
하단 영역을 충분히 확보하면 될 것 깉은데, 빈 영역으로 두면 벙번해 보일 수 있으니 copyright 를 넣어두면 어떨까 해요.

**Comment by ahnsungjoon** [comment]
@sogoonii 요렇게 넣죠. 자리는 현재 상품리스트 맨끝에 '----더보기---- ' 나오는 영역에 넣음 좋겠구요. 
Copyright © 2019 Team Second Market. All Rights Reserved. 
텍스트컬러는 #999999 로요.
