### ISSUE TITLE
상품상세 좌측 상단 돌아가기 버튼 우측에 홈버튼 노출

### ISSUE THREAD

**Issue by ahnsungjoon** [2nd-market/2nd-market#5]
상품상세에서 판매자의 다른 상품을 타고타고 구경을 하다보면 홈으로 가기가 어려움.
상품상세 좌측 상단에 홈 버튼을 노출.

**Comment by sogoonii** [comment]
상세페이지에서 홈으로 갈 수 있도록 타이틀바 **2nd Market** 텍스트에 링크 추가했습니다.

![image](https://user-images.githubusercontent.com/1967642/54808505-bb868600-4cc3-11e9-853d-59eac40616d1.png)

**Comment by ahnsungjoon** [comment]
상품상세에서 홈바로가기 잘 동작하는거 확인했어요~
